namespace FiveMDiagnostics.Tests;

using FiveMDiagnostics.Collectors;
using FiveMDiagnostics.Core;

/// <summary>
/// The texture budget as it survives contact with a real machine: a file with Windows line endings, a
/// value somebody typed by hand, and both files moving while the session runs.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="TextureBudgetTests"/> established the arithmetic and then asserted it against fixtures
/// this repository writes, which have Unix line endings because the source files do. Every
/// <c>fivem.cfg</c> the client writes has CRLF, and the regular expression that reads it anchored on a
/// line feed with nothing allowed in front of it — so on the machine the app was written for the line
/// never matched, the reading came back as "no such line, therefore the default", and every budget
/// stated all evening was 2.93 GB against a client that had been given 5.6.
/// </para>
/// <para>
/// The rest of these are the same class of defect: a state the fixtures never produced. A negative
/// convar, a value above the slider, a file that disappears mid-session, two files that move in the same
/// five minutes.
/// </para>
/// </remarks>
public sealed class ClientConfigIsReadFromRealFilesTests
{
    private static readonly DateTimeOffset Start = new(2026, 9, 3, 20, 11, 0, TimeSpan.Zero);

    private const ulong Gigabyte = 1024UL * 1024 * 1024;

    /// <summary>The line endings every client on Windows actually writes.</summary>
    [Fact]
    public void AConfigWithWindowsLineEndingsIsRead()
    {
        using var install = new FakeConfig(
            "// generated by CitizenFX\r\n"
            + "unbindall\r\n"
            + "seta \"cl_drawFPS\" \"false\"\r\n"
            + "seta \"vid_budgetScale\" \"11\"\r\n"
            + "seta \"voice_enableNoiseSuppression\" \"true\"\r\n");

        var config = install.Read();

        Assert.NotNull(config);
        Assert.Equal(11, config!.BudgetScale);
        Assert.Equal(5.615, config.TextureBudgetBytes / 1024d / 1024 / 1024, 3);
    }

    /// <summary>And the same file without them, which is what the fixtures had all along.</summary>
    [Fact]
    public void AConfigWithUnixLineEndingsIsStillRead()
    {
        using var install = new FakeConfig("seta \"vid_budgetScale\" \"11\"\n");

        Assert.Equal(11, install.Read()?.BudgetScale);
    }

    /// <summary>
    /// The last line of a file with no trailing newline, which is how a hand-edited one usually ends.
    /// </summary>
    [Fact]
    public void TheLineIsReadWhenItIsTheLastThingInTheFile()
    {
        using var install = new FakeConfig("seta \"cl_drawFPS\" \"false\"\r\nseta \"vid_budgetScale\" \"7\"");

        Assert.Equal(7, install.Read()?.BudgetScale);
    }

    /// <summary>
    /// A negative convar is a broken line, not a setting. It used to be arithmetic: <c>-12</c> gave a
    /// multiplier of zero and a budget of nothing, and <c>-24</c> gave a negative one that the cast to
    /// <see cref="ulong"/> turned into sixteen exabytes of streaming budget.
    /// </summary>
    [Theory]
    [InlineData(-1)]
    [InlineData(-12)]
    [InlineData(-24)]
    public void ANegativeValueIsReadAsTheDefaultAndSaidToBeWrong(int scale)
    {
        var config = new FiveMClientConfig("fivem.cfg", Start, scale);

        Assert.True(config.IsScaleOutOfRange);
        Assert.Equal(1.0, config.Multiplier, 3);
        Assert.Equal(FiveMClientConfig.BaseBudgetBytes, config.TextureBudgetBytes);
        Assert.Equal(0, config.SliderPercent);

        var described = config.Describe();
        Assert.Contains($"står på {scale}", described, StringComparison.Ordinal);
        Assert.Contains("ogiltigt värde", described, StringComparison.Ordinal);
    }

    /// <summary>
    /// A value above the slider's right end is honoured — the convar has no upper bound and the client
    /// will give the game that budget — but the percentage stops at the end of the control it describes.
    /// </summary>
    [Fact]
    public void AValueAboveTheSliderKeepsItsBudgetAndLosesItsPercentage()
    {
        var config = new FiveMClientConfig("fivem.cfg", Start, BudgetScale: 40);

        Assert.True(config.IsScaleOutOfRange);
        Assert.Equal(4.333, config.Multiplier, 3);
        Assert.Equal(100, config.SliderPercent);
        Assert.Contains("ovanför reglagets högsta läge", config.Describe(), StringComparison.Ordinal);
    }

    /// <summary>
    /// The recommendation is an instruction to move a control, so it may not name a position the control
    /// does not have. A 24 GB card with nothing else on it leaves room for a convar value of 60.
    /// </summary>
    [Fact]
    public void TheRecommendationStopsAtTheEndOfTheSlider()
    {
        var config = new FiveMClientConfig("fivem.cfg", Start, BudgetScale: 11);

        var advice = config.SuggestScale(roomForGame: 20UL * Gigabyte, overheadBytes: 0);

        Assert.Contains($"Extended Texture Budget {FiveMClientConfig.MaxScale}, ungefär 100 %", advice, StringComparison.Ordinal);
    }

    /// <summary>
    /// A new ceiling retires the warnings given against the old one, and the overhead measured against
    /// it. Lowering the slider two steps used to leave the monitor silent while quietly <em>raising</em>
    /// the recorded overhead by the difference between the two budgets.
    /// </summary>
    [Fact]
    public void ChangingTheBudgetMidSessionRearmsTheWarningsAndForgetsTheOverhead()
    {
        var monitor = new VramBudgetMonitor();
        monitor.SetTextureBudget(new FiveMClientConfig("fivem.cfg", Start, BudgetScale: 11));

        monitor.Observe(Adapter(Start, usedGigabytes: 8.87));
        monitor.Observe(Sample(Start, gameGigabytes: 7.00));

        var first = monitor.DescribeBudgetApproach();
        Assert.NotNull(first);
        Assert.Contains("5,6 GB", first!, StringComparison.Ordinal);
        Assert.True(monitor.OverheadBytes > 0);

        // Said once against that ceiling.
        Assert.Null(monitor.DescribeBudgetApproach());

        // The slider comes down two steps, which is the entire reason the file is re-read.
        var later = Start.AddMinutes(20);
        monitor.SetTextureBudget(new FiveMClientConfig("fivem.cfg", later, BudgetScale: 4));
        Assert.Equal(0UL, monitor.OverheadBytes);

        monitor.Observe(Adapter(later, usedGigabytes: 8.87));
        monitor.Observe(Sample(later, gameGigabytes: 7.00));

        var second = monitor.DescribeBudgetApproach();

        Assert.NotNull(second);
        Assert.Contains("3,9 GB", second!, StringComparison.Ordinal);
    }

    /// <summary>
    /// A file rewritten with the same value changes no ceiling, so it must not re-arm anything. A client
    /// that rewrites its configuration would otherwise repeat the same warning all evening.
    /// </summary>
    [Fact]
    public void RereadingTheSameBudgetSaysNothingASecondTime()
    {
        var monitor = new VramBudgetMonitor();
        monitor.SetTextureBudget(new FiveMClientConfig("fivem.cfg", Start, BudgetScale: 11));

        monitor.Observe(Adapter(Start, usedGigabytes: 8.87));
        monitor.Observe(Sample(Start, gameGigabytes: 7.00));
        Assert.NotNull(monitor.DescribeBudgetApproach());

        var overhead = monitor.OverheadBytes;
        monitor.SetTextureBudget(new FiveMClientConfig("fivem.cfg", Start.AddMinutes(5), BudgetScale: 11));

        Assert.Equal(overhead, monitor.OverheadBytes);
        Assert.Null(monitor.DescribeBudgetApproach());
    }

    /// <summary>
    /// Both files are read in the same call, so both changes have to come out of it. Returning on the
    /// budget threw the graphics change away for good: the reading it would have been compared against
    /// had already been replaced by the one that was discarded.
    /// </summary>
    [Fact]
    public void BothFilesMovingInTheSameIntervalAreBothReported()
    {
        using var install = new FakeInstall();
        var monitor = install.Monitor();

        Assert.Equal(2, monitor.DescribeInitial().Count);

        install.WriteConfig(scale: 8);
        install.WriteSettings(textureQuality: "1");

        var change = monitor.DescribeChange();

        Assert.NotNull(change);
        Assert.Contains("Extended Texture Budget ändrades under sessionen: 11 → 8", change!, StringComparison.Ordinal);
        Assert.Contains("TextureQuality 2 → 1", change, StringComparison.Ordinal);
    }

    /// <summary>
    /// A configuration file that disappears is reported once and then forgotten. Holding the last
    /// successful reading re-reported the disappearance on every check for the rest of the evening, and
    /// left the budget monitor measuring against a ceiling from a file that is not there.
    /// </summary>
    [Fact]
    public void AConfigThatDisappearsIsReportedOnceAndThenUnknown()
    {
        using var install = new FakeInstall();
        var monitor = install.Monitor();

        monitor.DescribeInitial();
        Assert.NotNull(monitor.ClientConfig);

        install.DeleteConfig();

        var change = monitor.DescribeChange();

        Assert.NotNull(change);
        Assert.Contains("klientkonfiguration kan inte längre läsas", change!, StringComparison.Ordinal);
        Assert.Null(monitor.ClientConfig);

        // Nothing moved since, so there is nothing to say.
        Assert.Null(monitor.DescribeChange());
    }

    /// <summary>
    /// The same for the graphics file, and with it the window mode: nothing can be read, so nothing is
    /// known, and the compositor goes back to being unexplained.
    /// </summary>
    [Fact]
    public void SettingsThatDisappearStopExplainingTheCompositor()
    {
        using var install = new FakeInstall();
        var monitor = install.Monitor();

        monitor.DescribeInitial();
        Assert.True(monitor.ExplainsComposedPresent);

        install.DeleteSettings();

        var change = monitor.DescribeChange();

        Assert.NotNull(change);
        Assert.Contains("kan inte längre läsas", change!, StringComparison.Ordinal);
        Assert.False(monitor.ExplainsComposedPresent);
        Assert.Null(monitor.DescribeChange());
    }

    private static GpuTelemetrySample Adapter(DateTimeOffset timestamp, double usedGigabytes) =>
        new(
            timestamp,
            IsAvailable: true,
            "NVIDIA GeForce RTX 3080",
            UtilizationPercent: 40,
            MemoryBandwidthUtilizationPercent: 21,
            UsedVramBytes: (ulong)(usedGigabytes * Gigabyte),
            TotalVramBytes: 10UL * Gigabyte,
            EncoderUtilizationPercent: 36,
            DecoderUtilizationPercent: 0,
            TemperatureCelsius: 59,
            ThrottleReasons: [],
            AdapterCount: 1);

    private static GpuProcessMemorySample Sample(DateTimeOffset timestamp, double gameGigabytes) =>
        new(
            timestamp,
            IsAvailable: true,
            [
                new GpuProcessMemoryUsage(31076, "FiveM_b3407_GTAProcess", (ulong)(gameGigabytes * Gigabyte), 0, 1),
                new GpuProcessMemoryUsage(7548, "obs64", (ulong)(0.9 * Gigabyte), 0, 1),
                new GpuProcessMemoryUsage(2244, "dwm", (ulong)(1.33 * Gigabyte), 0, 1),
            ]);

    /// <summary>One <c>fivem.cfg</c> on disk, written exactly as given.</summary>
    private sealed class FakeConfig : IDisposable
    {
        private readonly string _root;
        private readonly string _path;

        public FakeConfig(string contents)
        {
            _root = Path.Combine(Path.GetTempPath(), "fivemdiag-crlf-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_root);
            _path = Path.Combine(_root, "fivem.cfg");
            File.WriteAllText(_path, contents);
        }

        public FiveMClientConfig? Read() => FiveMClientConfigReader.Read([_path]);

        public void Dispose()
        {
            try
            {
                Directory.Delete(_root, recursive: true);
            }
            catch (IOException)
            {
            }
        }
    }

    /// <summary>
    /// Both files the session reads, in one directory, writable and deletable while a monitor watches
    /// them.
    /// </summary>
    private sealed class FakeInstall : IDisposable
    {
        private readonly string _root;
        private readonly string _settingsPath;
        private readonly string _configPath;
        private int _writes;

        public FakeInstall()
        {
            _root = Path.Combine(Path.GetTempPath(), "fivemdiag-install-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_root);
            _settingsPath = Path.Combine(_root, "gta5_settings.xml");
            _configPath = Path.Combine(_root, "fivem.cfg");

            WriteSettings("2");
            WriteConfig(11);
        }

        public GameGraphicsSettingsMonitor Monitor() =>
            new(Start, [_settingsPath], [_configPath]);

        /// <summary>
        /// Written with an explicit timestamp: both readings compare write times, and two writes inside
        /// one file system timestamp tick would otherwise look like no change at all.
        /// </summary>
        public void WriteSettings(string textureQuality)
        {
            File.WriteAllText(_settingsPath, $"""
                <?xml version="1.0" encoding="UTF-8"?>
                <Settings>
                  <graphics>
                    <TextureQuality value="{textureQuality}" />
                    <MSAA value="2" />
                  </graphics>
                  <video>
                    <ScreenWidth value="2560" />
                    <ScreenHeight value="1440" />
                    <Windowed value="2" />
                  </video>
                </Settings>
                """);

            Touch(_settingsPath);
        }

        public void WriteConfig(int scale)
        {
            File.WriteAllText(_configPath, $"seta \"cl_drawFPS\" \"false\"\r\nseta \"vid_budgetScale\" \"{scale}\"\r\n");
            Touch(_configPath);
        }

        public void DeleteConfig() => File.Delete(_configPath);

        public void DeleteSettings() => File.Delete(_settingsPath);

        private void Touch(string path) =>
            File.SetLastWriteTimeUtc(path, Start.UtcDateTime.AddMinutes(++_writes));

        public void Dispose()
        {
            try
            {
                Directory.Delete(_root, recursive: true);
            }
            catch (IOException)
            {
            }
        }
    }
}
