namespace FiveMDiagnostics.Tests;

using FiveMDiagnostics.Collectors;
using FiveMDiagnostics.Core;

/// <summary>
/// The setting the whole investigation was looking for, and the arithmetic that turns it into gigabytes.
/// </summary>
/// <remarks>
/// <para>
/// Twelve sessions asked what graphics settings the game was running. The answer was two files in
/// <c>%appdata%\CitizenFX</c>: <c>gta5_settings.xml</c>, which the reader searched for under the wrong
/// name, and <c>fivem.cfg</c>, which nothing read at all. The second holds
/// <c>seta "vid_budgetScale" "11"</c> — the client's own <em>Extended Texture Budget</em> slider.
/// </para>
/// <para>
/// These tests spent a day asserting the wrong arithmetic. They were written against
/// <c>11/8 + 1 = 2.375</c> on a 3.0 GiB base, which is the formula CitizenFX shipped in 2021 and
/// replaced on 12 November 2022 (76f4a54) — for exactly the reason this investigation ran into, that
/// people were exhausting real VRAM with the settings the old divisor gave them. Master computes
/// <c>(value / 12.0f) + 1.0f</c> on <c>3 * GB</c> where <c>GB</c> is <c>1000 * 1024 * 1024</c>, so 11
/// is 1.917× on 2.93 GiB: <b>5.6 GB, not 7.1</b>, and roughly 55 % on a slider that shows percent.
/// </para>
/// <para>
/// The measured plateau over the following five hours was 6.63 GB median and 7.63 GB peak — a gigabyte
/// <em>above</em> the streaming budget rather than just below it. That gap is the real finding: the
/// slider governs streaming, and NUI, render targets and the 1440p/2× MSAA frame buffers are paid on
/// top of it. Every verdict below is therefore stated against budget plus measured overhead, because
/// the budget alone would call this configuration comfortable.
/// </para>
/// </remarks>
public sealed class TextureBudgetTests
{
    /// <summary>The evening's own value, and the budget it produces.</summary>
    [Fact]
    public void TheSliderValueBecomesAFigureInGigabytes()
    {
        using var install = new FakeConfig("""
            // generated by CitizenFX
            unbindall
            seta "cl_drawFPS" "false"
            seta "vid_budgetScale" "11"
            seta "voice_enableNoiseSuppression" "true"
            """);

        var config = install.Read();

        Assert.NotNull(config);
        Assert.Equal(11, config!.BudgetScale);
        Assert.Equal(1.917, config.Multiplier, 3);

        // 2.93 GiB × 1.917. The measured plateau was 6.63 GB median, which is a gigabyte above this
        // and not below it — see TheGameHoldsMoreThanItsBudgetAndTheAdviceSaysSo.
        Assert.Equal(5.615, config.TextureBudgetBytes / 1024d / 1024 / 1024, 3);

        var described = config.Describe();
        Assert.Contains("Extended Texture Budget står på 11", described, StringComparison.Ordinal);
        Assert.Contains("5,6 GB", described, StringComparison.Ordinal);

        // The pause menu shows percent and nothing else, so whoever is asked to change it needs one.
        Assert.Equal(55, config.SliderPercent);
        Assert.Contains("ungefär 55 %", described, StringComparison.Ordinal);

        // And it must not be read as the game's whole appetite, which is what 2 September did.
        Assert.Contains("ligger ovanpå", described, StringComparison.Ordinal);
    }

    /// <summary>
    /// The divisor, pinned against the client's own worked example so it cannot quietly go back to 8.
    /// </summary>
    /// <remarks>
    /// A CitizenFX developer put 40 % at <c>vid_budgetScale 8</c>. Under the 2021 formula that value
    /// would be 4.5 GiB against a 3.0 base; under the one master actually ships it is 4.88 GB against
    /// 2.93. The whole correction of 3 September is one assertion wide.
    /// </remarks>
    [Fact]
    public void TheClientsDivisorIsTwelveAndTheBaseIsTheClientsOwnGigabyte()
    {
        Assert.Equal(12d, FiveMClientConfig.ScaleDivisor);
        Assert.Equal(3UL * 1000 * 1024 * 1024, FiveMClientConfig.BaseBudgetBytes);

        var forty = new FiveMClientConfig("fivem.cfg", DateTimeOffset.UtcNow, BudgetScale: 8);

        Assert.Equal(40, forty.SliderPercent);
        Assert.Equal(4.883, forty.TextureBudgetBytes / 1024d / 1024 / 1024, 3);
    }

    /// <summary>
    /// No line means the slider is where it shipped, and the game gets the base budget. Silence is a
    /// value here, not a missing measurement.
    /// </summary>
    [Fact]
    public void AConfigWithoutTheLineIsTheDefaultBudget()
    {
        using var install = new FakeConfig("""
            // generated by CitizenFX
            seta "cl_drawFPS" "false"
            """);

        var config = install.Read();

        Assert.NotNull(config);
        Assert.Null(config!.BudgetScale);
        Assert.Equal(1.0, config.Multiplier, 3);
        Assert.Contains("standardvärde", config.Describe(), StringComparison.Ordinal);
    }

    /// <summary>
    /// The verdict against the card, once what the slider does not govern is counted with it.
    /// </summary>
    /// <remarks>
    /// 10 GB card, 1.87 GB measured outside the game, band at 88 %: 6.93 GB for the game. The budget at
    /// 11 is 5.62 and fits on its own — but the evening's peak was 7.63 GB of game, so 2.0 GB of it was
    /// never the slider's to give. Budget plus that overhead is 7.6 against 6.93, and the largest value
    /// that fits once the overhead is paid for is 8, at roughly 40 % of the slider.
    /// </remarks>
    [Fact]
    public void TheGameHoldsMoreThanItsBudgetAndTheAdviceSaysSo()
    {
        var config = new FiveMClientConfig("fivem.cfg", DateTimeOffset.UtcNow, BudgetScale: 11);

        var verdict = config.DescribeAgainstCard(
            cardTotalBytes: 10UL * 1024 * 1024 * 1024,
            reservedBytes: (ulong)(1.87 * 1024 * 1024 * 1024),
            bandPercent: 88,
            overheadBytes: 2UL * 1024 * 1024 * 1024);

        Assert.NotNull(verdict);
        Assert.Contains("större än vad kortet klarar", verdict!, StringComparison.Ordinal);
        Assert.Contains("2,0 GB som mätts ovanpå budgeten", verdict, StringComparison.Ordinal);

        Assert.Contains("Extended Texture Budget 8, ungefär 40 %", verdict, StringComparison.Ordinal);
        Assert.Contains("4,9 GB", verdict, StringComparison.Ordinal);

        // The advice has to survive being followed by somebody who cannot see the server's map load.
        Assert.Contains("ett steg i taget", verdict, StringComparison.Ordinal);
    }

    /// <summary>A budget that fits says nothing, because a budget that fits is not news.</summary>
    [Fact]
    public void ABudgetThatFitsIsSilent()
    {
        var config = new FiveMClientConfig("fivem.cfg", DateTimeOffset.UtcNow, BudgetScale: 4);

        Assert.Null(config.DescribeAgainstCard(
            cardTotalBytes: 10UL * 1024 * 1024 * 1024,
            reservedBytes: 2UL * 1024 * 1024 * 1024,
            bandPercent: 88,
            overheadBytes: 0));
    }

    /// <summary>
    /// The value the report of 2 September called the cause fits the card on its own, and until the
    /// overhead has actually been measured the app says nothing about it.
    /// </summary>
    /// <remarks>
    /// This is the assertion the old divisor would fail. Under <c>/8</c> the budget at 11 was 7.13 GB
    /// against 6.93 of room and the app declared it too large at session start, on every machine, from
    /// a config file alone — a whole finding manufactured by arithmetic that had been out of date for
    /// four years.
    /// </remarks>
    [Fact]
    public void TheEveningsOwnSliderValueFitsUntilSomethingIsMeasuredOnTopOfIt()
    {
        var config = new FiveMClientConfig("fivem.cfg", DateTimeOffset.UtcNow, BudgetScale: 11);

        Assert.Null(config.DescribeAgainstCard(
            cardTotalBytes: 10UL * 1024 * 1024 * 1024,
            reservedBytes: (ulong)(1.87 * 1024 * 1024 * 1024),
            bandPercent: 88,
            overheadBytes: 0));
    }

    /// <summary>
    /// A card so crowded that even the default budget will not fit says the reglage is not the lever.
    /// </summary>
    [Fact]
    public void ACardWithNoRoomAtAllSaysTheSliderCannotFixIt()
    {
        var config = new FiveMClientConfig("fivem.cfg", DateTimeOffset.UtcNow, BudgetScale: 11);

        var verdict = config.DescribeAgainstCard(
            cardTotalBytes: 6UL * 1024 * 1024 * 1024,
            reservedBytes: 4UL * 1024 * 1024 * 1024,
            bandPercent: 88,
            overheadBytes: 0);

        Assert.NotNull(verdict);
        Assert.Contains("något annat måste bort från kortet", verdict!, StringComparison.Ordinal);
    }

    /// <summary>
    /// The filename that cost twelve sessions. FiveM writes <c>gta5_settings.xml</c>, and the reader was
    /// looking in the right directory for <c>settings.xml</c>.
    /// </summary>
    [Fact]
    public void TheClientsOwnSettingsFileIsFoundByItsRealName()
    {
        var root = Path.Combine(Path.GetTempPath(), "fivemdiag-citizenfx-" + Guid.NewGuid().ToString("N"));
        var directory = Path.Combine(root, "CitizenFX");
        Directory.CreateDirectory(directory);

        var path = Path.Combine(directory, "gta5_settings.xml");
        File.WriteAllText(path, """
            <?xml version="1.0" encoding="UTF-8"?>
            <Settings>
              <graphics>
                <TextureQuality value="2" />
                <MSAA value="2" />
                <ReflectionMSAA value="4" />
              </graphics>
              <video>
                <ScreenWidth value="2560" />
                <ScreenHeight value="1440" />
                <RefreshRate value="59" />
                <Windowed value="2" />
              </video>
            </Settings>
            """);

        try
        {
            var settings = GameGraphicsSettingsReader.Read([path], out _);

            Assert.NotNull(settings);
            Assert.Equal("2", settings!.Values["TextureQuality"]);
            Assert.Equal("2", settings.Values["Windowed"]);

            // Borderless, so the composed present path is configuration rather than a finding.
            Assert.True(settings.ExplainsComposedPresent);
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>Exclusive fullscreen explains nothing about a compositor, so it must not claim to.</summary>
    [Fact]
    public void ExclusiveFullscreenDoesNotExplainAComposedPresentPath()
    {
        var settings = new GameGraphicsSettings(
            "settings.xml",
            DateTimeOffset.UtcNow,
            new Dictionary<string, string> { ["Windowed"] = "0" },
            WindowModeNote: string.Empty);

        Assert.False(settings.ExplainsComposedPresent);
    }

    private sealed class FakeConfig : IDisposable
    {
        private readonly string _root;
        private readonly string _path;

        public FakeConfig(string contents)
        {
            _root = Path.Combine(Path.GetTempPath(), "fivemdiag-cfg-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_root);
            _path = Path.Combine(_root, "fivem.cfg");
            File.WriteAllText(_path, contents);
        }

        public FiveMClientConfig? Read() => FiveMClientConfigReader.Read([_path]);

        public void Dispose()
        {
            try
            {
                Directory.Delete(_root, recursive: true);
            }
            catch (IOException)
            {
            }
        }
    }
}
