// <auto-generated />

#nullable enable

using System.Globalization;
using System.Resources;

namespace FiveMDiagnostics.App.Wpf.Properties;

public static class Strings
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("FiveMDiagnostics.App.Wpf.Properties.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string AppTitle => ResourceManager.GetString("AppTitle", Culture) ?? "FiveM Diagnostics";
    public static string AppSubtitle => ResourceManager.GetString("AppSubtitle", Culture) ?? "";
    public static string AlreadyRunningMessage => ResourceManager.GetString("AlreadyRunningMessage", Culture) ?? "FiveM Diagnostics is already running, but the running window did not respond. Look for the icon in the notification area.";
    public static string StateLabel =>ResourceManager.GetString("StateLabel", Culture) ?? "State:";
    public static string ActiveProcessLabel => ResourceManager.GetString("ActiveProcessLabel", Culture) ?? "Active process:";
    public static string QuickStartHeader => ResourceManager.GetString("QuickStartHeader", Culture) ?? "How it works";
    public static string QuickStartIntro => ResourceManager.GetString("QuickStartIntro", Culture) ?? "Start a session and play. There is no mode to pick — the app always collects system, process and network evidence.";
    public static string QuickStartStepOne => ResourceManager.GetString("QuickStartStepOne", Culture) ?? "1. Start the session.";
    public static string QuickStartStepTwo => ResourceManager.GetString("QuickStartStepTwo", Culture) ?? "2. Mark stutter when it happens.";
    public static string QuickStartStepThree => ResourceManager.GetString("QuickStartStepThree", Culture) ?? "3. Export the latest incident when you're done.";
    public static string QuickStartDeepNote => ResourceManager.GetString("QuickStartDeepNote", Culture) ?? "Mark severe stutter additionally starts a short WPR trace. That is automatic and requires the app to run as administrator.";
    public static string PresentMonStatusLabel => ResourceManager.GetString("PresentMonStatusLabel", Culture) ?? "Frame telemetry";
    public static string PresentMonStatusConfigured => ResourceManager.GetString("PresentMonStatusConfigured", Culture) ?? "PresentMon is configured. Frame telemetry will be included.";
    public static string PresentMonStatusAutoDetected => ResourceManager.GetString("PresentMonStatusAutoDetected", Culture) ?? "PresentMon was found automatically. No manual path is needed.";
    public static string PresentMonStatusMissing => ResourceManager.GetString("PresentMonStatusMissing", Culture) ?? "PresentMon was not found. The app still works without it; add it later under Advanced if you want deeper frame data.";
    public static string CaptureFeedbackHeader => ResourceManager.GetString("CaptureFeedbackHeader", Culture) ?? "Capture status";
    public static string CaptureFeedbackHint => ResourceManager.GetString("CaptureFeedbackHint", Culture) ?? "When you mark stutter, the app keeps collecting for another 60 seconds before the finished incident appears in the list.";
    public static string CaptureFeedbackSessionStarted => ResourceManager.GetString("CaptureFeedbackSessionStarted", Culture) ?? "Session started. Waiting for PresentMon frames and the 30-second pre-buffer.";
    public static string CaptureFeedbackCollectingFormat => ResourceManager.GetString("CaptureFeedbackCollectingFormat", Culture) ?? "{0} saved. The app understood the click and is collecting the rest of the capture window until {1}. Pending captures: {2}.";
    public static string CaptureFeedbackReadyFormat => ResourceManager.GetString("CaptureFeedbackReadyFormat", Culture) ?? "{0} is now ready. Select it in the incident list to inspect the analysis.";
    public static string CaptureFeedbackReadyWithPendingFormat => ResourceManager.GetString("CaptureFeedbackReadyWithPendingFormat", Culture) ?? "{0} is now ready. There are still {1} capture(s) being collected.";
    public static string CaptureFeedbackSyntheticReady => ResourceManager.GetString("CaptureFeedbackSyntheticReady", Culture) ?? "Synthetic incident created immediately for testing.";

    public static string PacingHeader => ResourceManager.GetString("PacingHeader", Culture) ?? "Frame pacing this session";
    public static string PacingIdle => ResourceManager.GetString("PacingIdle", Culture) ?? "No frame pacing data yet. The first window closes after a minute of frames.";
    public static string PacingSaturatedLabel => ResourceManager.GetString("PacingSaturatedLabel", Culture) ?? "Could not hold the frame rate:";
    public static string PacingWorstLabel => ResourceManager.GetString("PacingWorstLabel", Culture) ?? "Worst minute:";
    public static string PacingCurrentLabel => ResourceManager.GetString("PacingCurrentLabel", Culture) ?? "Right now:";
    public static string PacingCaptureBudgetLabel => ResourceManager.GetString("PacingCaptureBudgetLabel", Culture) ?? "Deep captures left:";
    public static string PacingSaturatedFormat => ResourceManager.GetString("PacingSaturatedFormat", Culture) ?? "{0} of {1} min ({2}), {3} marginal. Longest unbroken stretch {4} min.";
    public static string PacingWorstFormat => ResourceManager.GetString("PacingWorstFormat", Culture) ?? "{0} fps against a target of {1}";
    public static string PacingCurrentFormat => ResourceManager.GetString("PacingCurrentFormat", Culture) ?? "{0} — {1} fps, CPU headroom {2} ms";
    public static string PacingCurrentNoHeadroomFormat => ResourceManager.GetString("PacingCurrentNoHeadroomFormat", Culture) ?? "{0} — {1} fps";
    public static string PacingCaptureBudgetFormat => ResourceManager.GetString("PacingCaptureBudgetFormat", Culture) ?? "{0} of {1}";

    public static string ControlsHeader => ResourceManager.GetString("ControlsHeader", Culture) ?? "Controls";
    public static string SessionGroup => ResourceManager.GetString("SessionGroup", Culture) ?? "Quick start";
    public static string StartSession => ResourceManager.GetString("StartSession", Culture) ?? "Start session";
    public static string StopSession => ResourceManager.GetString("StopSession", Culture) ?? "Stop Session";
    public static string IncidentActionsGroup => ResourceManager.GetString("IncidentActionsGroup", Culture) ?? "During gameplay";
    public static string MarkStutter => ResourceManager.GetString("MarkStutter", Culture) ?? "Mark Stutter";
    public static string MarkSevere => ResourceManager.GetString("MarkSevere", Culture) ?? "Mark severe stutter";
    public static string DataGroup => ResourceManager.GetString("DataGroup", Culture) ?? "Afterwards";
    public static string ExportLatest => ResourceManager.GetString("ExportLatest", Culture) ?? "Export Latest";
    public static string ImportArtifacts => ResourceManager.GetString("ImportArtifacts", Culture) ?? "Add extra files";

    public static string SettingsHeader => ResourceManager.GetString("SettingsHeader", Culture) ?? "Optional setup";
    public static string ServerProfile => ResourceManager.GetString("ServerProfile", Culture) ?? "Server profile";
    public static string ServerProfileHint => ResourceManager.GetString("ServerProfileHint", Culture) ?? "Only used as a label in the incident list and exports.";
    public static string ProbeHost => ResourceManager.GetString("ProbeHost", Culture) ?? "Probe host / IP";
    public static string ProbeHostHint => ResourceManager.GetString("ProbeHostHint", Culture) ?? "Fill this in only if you know the game server host or IP and want ping samples.";
    public static string EndpointHint => ResourceManager.GetString("EndpointHint", Culture) ?? "Endpoint hint (optional host:port)";
    public static string EndpointHintDescription => ResourceManager.GetString("EndpointHintDescription", Culture) ?? "Optional readable host:port label for detected connections. Leave blank if you are unsure.";
    public static string SettingsIntro => ResourceManager.GetString("SettingsIntro", Culture) ?? "Start with quick start. Everything below is optional and only needed for extra context or custom folders.";
    public static string NetworkHintsHeader => ResourceManager.GetString("NetworkHintsHeader", Culture) ?? "Optional network hints";
    public static string NetworkHintsDescription => ResourceManager.GetString("NetworkHintsDescription", Culture) ?? "Use these only if you want extra network context in the incident timeline.";
    public static string AdvancedSettings => ResourceManager.GetString("AdvancedSettings", Culture) ?? "Advanced Settings";
    public static string AdvancedSettingsDescription => ResourceManager.GetString("AdvancedSettingsDescription", Culture) ?? "Only open this if you need custom folders or want to override PresentMon/WPR paths.";
    public static string PresentMonPath => ResourceManager.GetString("PresentMonPath", Culture) ?? "PresentMon executable path";
    public static string WorkingDirectory => ResourceManager.GetString("WorkingDirectory", Culture) ?? "Working directory";
    public static string ExportDirectory => ResourceManager.GetString("ExportDirectory", Culture) ?? "Export directory";
    public static string ArtifactDirectory => ResourceManager.GetString("ArtifactDirectory", Culture) ?? "Artifact directory";
    public static string AutoDetectEnabled => ResourceManager.GetString("AutoDetectEnabled", Culture) ?? "Mark stutters automatically (no hotkey needed)";
    public static string IncludeSensitiveFields => ResourceManager.GetString("IncludeSensitiveFields", Culture) ?? "Include sensitive fields in export";
    public static string IncludeAttachedArtifacts => ResourceManager.GetString("IncludeAttachedArtifacts", Culture) ?? "Include attached artifacts in export";
    public static string SaveSettings => ResourceManager.GetString("SaveSettings", Culture) ?? "Save Settings";
    public static string LanguageLabel => ResourceManager.GetString("LanguageLabel", Culture) ?? "Language";
    public static string LanguageChangeHint => ResourceManager.GetString("LanguageChangeHint", Culture) ?? "Restart the app to apply language changes.";
    public static string EnglishLanguageName => ResourceManager.GetString("EnglishLanguageName", Culture) ?? "English";
    public static string SwedishLanguageName => ResourceManager.GetString("SwedishLanguageName", Culture) ?? "Swedish";
    public static string TrayHeader => ResourceManager.GetString("TrayHeader", Culture) ?? "Tray menu";
    public static string TrayIntro => ResourceManager.GetString("TrayIntro", Culture) ?? "Right-click the tray icon to control diagnostics without reopening the window.";
    public static string TrayStartStop => ResourceManager.GetString("TrayStartStop", Culture) ?? "Start or stop sessions directly from the tray.";
    public static string TrayMark => ResourceManager.GetString("TrayMark", Culture) ?? "Mark normal or severe stutter from the tray menu while a session is active.";
    public static string TrayExport => ResourceManager.GetString("TrayExport", Culture) ?? "Export the latest incident from the tray when you want to capture evidence quickly.";
    public static string TrayShowWindow => ResourceManager.GetString("TrayShowWindow", Culture) ?? "Show window";
    public static string TrayExit => ResourceManager.GetString("TrayExit", Culture) ?? "Exit";
    public static string TrayReadyMessage => ResourceManager.GetString("TrayReadyMessage", Culture) ?? "Right-click the tray icon to control diagnostics.";
    public static string WindowMinimizedToTrayMessage => ResourceManager.GetString("WindowMinimizedToTrayMessage", Culture) ?? "Window minimized to tray.";
    public static string AppHiddenToTrayMessage => ResourceManager.GetString("AppHiddenToTrayMessage", Culture) ?? "App hidden to tray. Diagnostics can keep running in the background.";
    public static string TraySessionStartingMessage => ResourceManager.GetString("TraySessionStartingMessage", Culture) ?? "Session starting in the background.";
    public static string TraySessionStoppedMessage => ResourceManager.GetString("TraySessionStoppedMessage", Culture) ?? "Session stopped.";
    public static string TrayMarkStutterMessage => ResourceManager.GetString("TrayMarkStutterMessage", Culture) ?? "Stutter marked.";
    public static string TrayMarkSevereMessage => ResourceManager.GetString("TrayMarkSevereMessage", Culture) ?? "Severe stutter marked.";
    public static string TrayExportStartingMessage => ResourceManager.GetString("TrayExportStartingMessage", Culture) ?? "Exporting the latest incident.";

    public static string FakeDataHeader => ResourceManager.GetString("FakeDataHeader", Culture) ?? "Testing tools";
    public static string FakeDataDescription => ResourceManager.GetString("FakeDataDescription", Culture) ?? "";
    public static string SimulateObs => ResourceManager.GetString("SimulateObs", Culture) ?? "Simulate OBS/GPU contention";
    public static string SimulateResource => ResourceManager.GetString("SimulateResource", Culture) ?? "Simulate FiveM resource spike";
    public static string SimulateNetwork => ResourceManager.GetString("SimulateNetwork", Culture) ?? "Simulate network issue";

    public static string StatusLogHeader => ResourceManager.GetString("StatusLogHeader", Culture) ?? "Activity log";
    public static string RecentIncidentsHeader => ResourceManager.GetString("RecentIncidentsHeader", Culture) ?? "Recent Incidents";
    public static string MarkedColumn => ResourceManager.GetString("MarkedColumn", Culture) ?? "Marked";
    public static string SeverityColumn => ResourceManager.GetString("SeverityColumn", Culture) ?? "Severity";
    public static string ServerColumn => ResourceManager.GetString("ServerColumn", Culture) ?? "Server";
    public static string SummaryColumn => ResourceManager.GetString("SummaryColumn", Culture) ?? "Summary";
    public static string IncidentSummaryHeader => ResourceManager.GetString("IncidentSummaryHeader", Culture) ?? "Incident Summary";
    public static string RankedHypothesesHeader => ResourceManager.GetString("RankedHypothesesHeader", Culture) ?? "Ranked Hypotheses";
    public static string TimelineHeader => ResourceManager.GetString("TimelineHeader", Culture) ?? "Timeline";

    public static string SessionActive => ResourceManager.GetString("SessionActive", Culture) ?? "";
    public static string SessionWarmingUp => ResourceManager.GetString("SessionWarmingUp", Culture) ?? "Collecting PresentMon pre-buffer.";
    public static string SessionReady => ResourceManager.GetString("SessionReady", Culture) ?? "Ready for incident.";
    public static string CaptureFeedbackIncidentReady => ResourceManager.GetString("CaptureFeedbackIncidentReady", Culture) ?? "PresentMon is delivering frames and the 30-second pre-buffer is complete. Ready for incident.";
    public static string CaptureFeedbackWarmingFormat => ResourceManager.GetString("CaptureFeedbackWarmingFormat", Culture) ?? "Waiting for continuous PresentMon frames and pre-buffer: {0:F0}/{1:F0} seconds.";
    public static string CaptureNormalManualIncidents => ResourceManager.GetString("CaptureNormalManualIncidents", Culture) ?? "Deep capture for normal manual markers";
    public static string SessionIdle => ResourceManager.GetString("SessionIdle", Culture) ?? "";
    public static string WaitingForProcess => ResourceManager.GetString("WaitingForProcess", Culture) ?? "";
    public static string SelectIncidentHint => ResourceManager.GetString("SelectIncidentHint", Culture) ?? "";
    public static string SettingsSavedFormat => ResourceManager.GetString("SettingsSavedFormat", Culture) ?? "Settings saved to {0}.";
    public static string IncidentExportedTitle => ResourceManager.GetString("IncidentExportedTitle", Culture) ?? "Incident exported";

    public static string LiveCpuLabel => ResourceManager.GetString("LiveCpuLabel", Culture) ?? "CPU:";
    public static string LiveMemoryLabel => ResourceManager.GetString("LiveMemoryLabel", Culture) ?? "RAM:";
    public static string LiveRamFreeFormat => ResourceManager.GetString("LiveRamFreeFormat", Culture) ?? "{0} MB free";
    public static string LiveStatsIdle => ResourceManager.GetString("LiveStatsIdle", Culture) ?? "\u2014";
    public static string LiveVramLabel => ResourceManager.GetString("LiveVramLabel", Culture) ?? "VRAM:";
    public static string LiveVramFormat => ResourceManager.GetString("LiveVramFormat", Culture) ?? "{0} of {1} GB ({2}%)";
    public static string LiveVramUnavailable => ResourceManager.GetString("LiveVramUnavailable", Culture) ?? "n/a";
    public static string LiveVramOwnersLabel => ResourceManager.GetString("LiveVramOwnersLabel", Culture) ?? "Largest in VRAM:";
    public static string LiveVramPanelHeader => ResourceManager.GetString("LiveVramPanelHeader", Culture) ?? "What is holding VRAM";
    public static string LiveVramPanelDescription => ResourceManager.GetString("LiveVramPanelDescription", Culture) ?? "Live, refreshed with every sample. \"Taken\" is what a process has added since this session started — a program that took several hundred megabytes at once usually keeps them, and that is memory the game does not get.";
    public static string LiveVramColumnProcess => ResourceManager.GetString("LiveVramColumnProcess", Culture) ?? "Process";
    public static string LiveVramColumnNow => ResourceManager.GetString("LiveVramColumnNow", Culture) ?? "Now";
    public static string LiveVramColumnTaken => ResourceManager.GetString("LiveVramColumnTaken", Culture) ?? "Taken";
    public static string LiveVramColumnPeak => ResourceManager.GetString("LiveVramColumnPeak", Culture) ?? "Peak";
    public static string LiveVramUntrustedNote => ResourceManager.GetString("LiveVramUntrustedNote", Culture) ?? "double counted — excluded from reports";
    public static string LiveVramPanelEmpty => ResourceManager.GetString("LiveVramPanelEmpty", Culture) ?? "No process table yet. It appears once a session is running.";
    public static string SessionAlertsHeader => ResourceManager.GetString("SessionAlertsHeader", Culture) ?? "Needs attention";
    public static string LiveVramOwnersUnavailable => ResourceManager.GetString("LiveVramOwnersUnavailable", Culture) ?? "not measured";
}
